import type { Metadata } from 'next';
import { Archivo, Archivo_Black, Montserrat } from 'next/font/google';

import './globals.css';

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin'],
});

const archivoSans = Archivo({
	variable: '--font-archivo-sans',
	subsets: ['latin'],
});
const archivoBlackSans = Archivo({
	variable: '--font-archivo-black',
});

export const metadata: Metadata = {
	title: 'Imagining Life',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${montserratSans.variable} ${archivoSans.variable} ${archivoBlackSans.variable} antialiased`}>{children}</body>
		</html>
	);
}
