import type { Metadata } from 'next';
import { Archivo, Archivo_Black, Montserrat } from 'next/font/google';

import { SITE_NAME } from '@/constants/seo.constants';

import './globals.css';

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin'],
});

const archivoSans = Archivo({
	variable: '--font-archivo-sans',
	subsets: ['latin'],
});
const archivoBlackSans = Archivo({
	variable: '--font-archivo-black',
});

export const metadata: Metadata = {
	title: SITE_NAME,
	icons: {
		icon: '/favicon/favicon.ico',
		shortcut: '/favicon/favicon.ico',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${montserratSans.variable} ${archivoSans.variable} ${archivoBlackSans.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
